### ISSUE TITLE
better name handling in data.table:CJ

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3misc#11]
i have this code now here

https://github.com/mlr-org/paradox/blob/master/R/generate_design_grid.R

```
  # the un / renaming sucks a bit here, caused by dotdotdot-interface of CJ. would like to have a better way, but dont know
  # FIXME: mini helper in mlr3misc for this?
  ns = names(res); res = unname(res)
  res = do.call(CJ, c(res, sorted = FALSE))
  set_names(res, ns)
```

it sucks. problem is that res can contain "sorted". 

should we add a helper CJ(list, sorted) ?

I would rather avoid this, but the above sucks a lot and keeping CJ as it is, is buggy and unsafe

**Comment by berndbischl** [comment]
note to us: dotdotdot is for sucker, avoid

**Comment by mllg** [comment]
Also removed the workaround in paradox.
