### ISSUE TITLE
Suggestion: `set_attrs()` function

### ISSUE THREAD

**Issue by m-muecke** [mlr-org/mlr3misc#124]
Can we get a `set_attrs()` function for setting the attributes like the `set_class()`, `set_names()` or `set_params()`.

**Comment by be-marc** [comment]
We rarely use attributes but feel free to open a PR.

**Comment by mb706** [comment]
How would `set_attrs()` behave differently from `structure()`?

**Comment by m-muecke** [comment]
> How would `set_attrs()` behave differently from `structure()`?

Fair point, basically the same besides removing all attributes as well, being faster and having better name

```r
set_attrs = function(x, ...) {
  attrs = list(...)
  if (identical(attrs, list(NULL))) {
    attributes(x) = NULL
  } else {
    assert_list(attrs, names = "unique")
    attributes(x) = c(attributes(x), attrs)
  }
  x
}
``
