### ISSUE TITLE
can we please make transpose S3

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3misc#13]
i need to do special NA-handling in paradox, when a generated dt contains in some elements NAs.

when transponse generates the list of row-configurations, the user should have the option to filter out NAs quickly (before config-evaluation)

for this, I could set a class for returned dt-objects in paradox and then specialize transpose in paradox

connected issues

https://github.com/mlr-org/paradox/issues/140

**Comment by mllg** [comment]
paradox has its custom version of transpose now, and I'm still thinking about renaming transpose in mlr3misc to avoid name clashes (but this is another issue).
