### ISSUE TITLE
'transpose' nameclash with data.table transpose

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3misc#16]
The `transpose` function name-clashes with the `data.table::transpose` function. We usually import both these packages, so we end up having to write `mlr3misc::transpose`, while we usually don't prefix mlr3misc functions. Renaming this function to `transpose_list` would probably be more convenient. (We would be breaking with `purrr` function names).

**Comment by mllg** [comment]
https://github.com/mlr-org/mlr3misc/blob/master/R/zzz.R#L1 ?

**Comment by berndbischl** [comment]
> https://github.com/mlr-org/mlr3misc/blob/master/R/zzz.R#L1 ?

yes

**Comment by mllg** [comment]
Yes!
