### ISSUE TITLE
unnest: does not work with non-scalar columns

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3misc#31]
it is the underlying issue reported here 
https://github.com/mlr-org/mlr3tuning/issues/201

i guess the case / problem is very clear

a) we document this at least as a restriction that unnesting non-scalar columns is not possible
b) probably better: unnest the rest into individual list-columns

**Comment by mllg** [comment]
https://github.com/mlr-org/mlr3misc/pull/32

Does this help?

@mb706

**Comment by berndbischl** [comment]
i tested in mlr3tuning with the branch. it works
