### ISSUE TITLE
Suggestion: Compound assignment operators

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3misc#33]
We could define operators such as `%+=%`, `%-=%` etc. What I seem to need a lot is
```r
x = c(x, <something>)
```
so maybe we could have an `%c=%` operator for that.

See [here](https://github.com/mb706/automlr/blob/8e74e08d47a682430cfe0b793a9f290662868080/R/utils.R#L7-L10) for my implementation in an old project.

**Comment by berndbischl** [comment]
I am rather against changing the language thru the backdoor.
I know what you mean, I understand why you want that. But imho this is not the place. There is also not stopping if we do this.

**Comment by mllg** [comment]
Agreeing with Bernd, this only complicates things.
