### ISSUE TITLE
crate() function in mlr3misc

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3misc#50]
I wrote something similar to carrier::crate [here](https://github.com/mlr-org/paradox/blob/5bbfe201d408595633ac5ac6660fe862cdc4f4f7/R/helper.R#L117-L142). The difference is that `.fn` does not need to be a verbatim function definition, with the cost that all values being used need to be declared in `...`. Do we want this in mlr3misc? I think it would be generally helpful in places where functions are given to objects, e.g. in `ParamUty` constructor argument `custom_check`.

**Comment by mllg** [comment]
Yep, seems useful. I don't think that the name clash will be a problem.
