### ISSUE TITLE
I can't download mlr3 onto my Rstudio

### ISSUE THREAD

**Issue by DanielKim15** [mlr-org/mlr3misc#58]
I tried to install it on my rstudio, but it just won't work. I did:
1. install.packages("mlr3verse")
2. install.packages("mlr3")

Every time when I run the library(ml3rverse) or library(mlr3), I get this error:
Error: package or namespace load failed for ‘mlr3verse’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘mlr3misc’

I have the latest Rstudio, is there something else that's wrong?

**Comment by mllg** [comment]
Looks like `mlr3misc` is just not installed. #59 might have been the problem. If this problem persists, please reopen with the output of `install.packages("mlr3misc")`.
