### ISSUE TITLE
what is the best way to map an R6 method over a list of objects

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3misc#7]

**Comment by mllg** [comment]
```r
map(x, r6$method)
```
?

**Comment by berndbischl** [comment]
wouldnt it have to be
map(xs, function(x) x$method())
?
and then it is not type safe?

**Comment by mllg** [comment]
Ah, you have a list of R6 instances of the same class and you want to call a specific method of each instance?

Yes, then it is `map(xs, function(x) x$method())`

**Comment by berndbischl** [comment]
yes. for ABs / slots you can actually write
map(xs, "slot")

not sure why i opened this
