### ISSUE TITLE
Partial argument matching for dictionary sugar get

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3misc#83]
It is e.g. impossible for a learner with a parameter / field that partially matches `dict` to be set during a `lrn()` call as the value of this parameter will be used as the `dict` argument.

**Comment by mllg** [comment]
Can you provide a reproducible example for this?

**Comment by sebffischer** [comment]
``` r
library(mlr3misc)

dictionary = Dictionary$new()

dictionary$add("a", function(di) print(dictus))


sgr = function(.key, ...) {
  dictionary_sugar_get(dictionary, .key, ...)
}

sgr("a", di = "hallo")
#> Error in dictionary_sugar_get(dictionary, .key, ...): Assertion on 'dict' failed: Must inherit from class 'Dictionary', but has class 'character'.
```

<sup>Created on 2023-07-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by sebffischer** [comment]
The additional `di = "hallo"` partiall matches the `dict` argument from `dictionary_sugar_get`.
We could just call the `dict` argument `.dict`.

**Comment by mllg** [comment]
Agreed - can you PR this?

**Comment by sebffischer** [comment]
We need to sync PRs in packages though: https://github.com/mlr-org/mlr3pipelines/blob/dae03afd8efa83621a495a058f42cfc2ea8d7357/R/ppl.R#L26

Or we add an 
```
if (packageVersion("mlr3") > ...) 
  use .dict
else
  use dict
```

**Comment by mb706** [comment]
maybe better to create a new function `dictionary_sugar_get_safe` and remove the old function after a few versions, this way we don't all have to upload new packages
