### ISSUE TITLE
Bug in crate function

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3misc#87]
``` r
library(mlr3misc)

l = list(a = 1)

crate(function() print(a), a = l$a)
#> Error in vapply(.x, .f, FUN.VALUE = .value, USE.NAMES = FALSE, ...): values must be length 1,
#>  but FUN(X[[2]]) result is length 3
```

<sup>Created on 2023-08-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by sebffischer** [comment]
Ok this is no bug I think but at least something that can be improved

**Comment by mb706** [comment]
The way `crate()` is set up currently is that it only passes along variables from the surrounding environment to the crated environment. The benefit here is that the static code check done by `R CMD check` will not have any problems with this.

If `crate()` allowed what you are doing in your code, the code checker would admonish that the `function()` is referencing a non-existent variable `a`. `crate()` forcing you to write it as follows is therefore a good thing:

```r
library(mlr3misc)

l = list(a = 1)

a = l$a
crate(function() print(a), a)
```

**Comment by sebffischer** [comment]
thx!
