### ISSUE TITLE
consider adding of "reduce" function

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3misc#9]
aggregating lists down to a single element is an important operatuon. 
base R has "Reduce". I will at least have a look at what purrr does and see if it is beneficial

**Comment by berndbischl** [comment]
cannot put my finger on why Reduce is bad. (except for inconsistent naming).
will leave this open for now

**Comment by mllg** [comment]
`reduce = Reduce` does not seem to be an option here ;)
